<h1 id="add_a_new_contact">Add a new contact</h1>

<h2>Please complete this form</h2>

<?php echo $this->tag->form('add/register') ?>

	<p>
		<label for="name">Firstname : </label>
		<?php echo $this->tag->textField("firstname") ?>
	</p>
	
	<p>
		<label for="name">Lastname : </label>
		<?php echo $this->tag->textField("lastname") ?>
	</p>

	<p>
		<label for="name">E-Mail : </label>
		<?php echo $this->tag->textField("email") ?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Add contact") ?>
	</p>

</form>
